type User {
    _id: String
    username: String
    firstname: String
    lastname: String
}

type Query {
    users: [User]
    user(id: String!): User
}

type Mutation {
    newUser(username: String, firstname: String, lastname: String, password: String): User
}